### PR TITLE
Fix Changed-On date being 1 day behind

### LINKED ISSUE #68: Changed on subtracts one extra day
Take a look at the current values for DarFoundation:
```json
                "maghrib": {
                    "time": "6:22 PM",
                    "changed": true,
                    "changed_on": "2023-10-28"
                },
                "isha": {
                    "time": "7:45 PM",
                    "changed": true,
                    "changed_on": "2023-10-28"
                }
```
Take a look now on wwpray.net:

image

These should show today in the interface.

Now is 28-10 10:40am EST.

### PR DESCRIPTION
**Pull request by fayez-nazzal**
If we parse "28-10-2023", which isn't an ISO Date, it will be treated as 12:00AM, and then we compare it with the current UTC time that date will be older so it will be shown as "Yesterday" instead of "Today" and so on.

This PR gets the current time using the local time, it will be the same as the client timezone.

# Screenshot

image

### CODE REVIEW

**Comment by fayez-nazzal** [comment]
@hammady I'm still not sure though, I think it will be still UTC for the current time because when doing SSG it will compare to server time, I will add a browser check to move the timezone check to the client.

File: generator/svelte/src/lib/utils.ts [hunk 1]
```diff
@@ -16,10 +16,16 @@ export const convertToRelativeTime = (isoDate: string) => {
 	return dayjs.utc(isoDate).fromNow();
 };
 
-export const convertToCalendarTime = (isoDate?: string) => {
-	if (!isoDate) return null;
+export const convertToCalendarTime = (dateStr?: string) => {
+	if (!dateStr) return null;
 
+<<<<<<< Updated upstream
```
Comment (hammady) [inline generator/svelte/src/lib/utils.ts]: Please resolve conflicts.

**Review by hammady — CHANGES_REQUESTED** [review]

File: generator/svelte/src/lib/utils.ts (hunk 1 above)
Comment (fayez-nazzal) [reply generator/svelte/src/lib/utils.ts]: @hammady Updated, I added a screenshot in the description (after setting current datetime to Nov 26, all seems well)

**Review by hammady — APPROVED** [review]

File: generator/svelte/src/lib/utils.ts (hunk 1 above)
Comment (hammady) [reply generator/svelte/src/lib/utils.ts]: Great!
